[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = ["chmod +x entrypoint.sh"]

[phases.start]
cmd = "./entrypoint.sh"

[env]
ALLOWED_HOSTS = "127.0.0.1,localhost,moq.up.railway.app,moqq.up.railway.app,healthcheck.railway.app"
TOX_DEBUG = "False"
DJANGO_SETTINGS_MODULE = "tox.settings"
PORT = "8080"